apiVersion: v1
kind: Service
metadata:
  name: redis-stedi-stage
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-stedi-stage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stedi-stage
spec:
  selector:
    matchLabels:
      app: redis-stedi-stage  # has to match .spec.template.metadata.labels
  serviceName: redis-stedi-stage
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-stedi-stage  # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: redis-stedi-stage
          image: redis/redis-stack-server:latest
          imagePullPolicy: Always
          #args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              cpu: ".25"
              memory: "500Mi"
            requests:
              cpu: ".125"
              memory: ".0625Mi"
          env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-secrets-stage
                key: REDIS_PASS
          - name: REDIS_ARGS
            value: "--requirepass $(REDIS_PASS) --appendonly yes --save 900 1 --save 30 2"
          volumeMounts:
            - name: redis-stage-volume
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-stage-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

